(function(){
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const style=document.createElement('style');style.textContent=`html{--motion-ease:cubic-bezier(.22,1,.36,1);--motion-fast:180ms;--motion-mid:520ms}@media (prefers-reduced-motion:no-preference){body.motion-ready .masthead,body.motion-ready .menu,body.motion-ready .page>*{animation:sm-enter .7s var(--motion-ease) both}.menu a{position:relative;transition:color var(--motion-fast) ease,transform var(--motion-fast) var(--motion-ease)}.menu a:after{content:'';position:absolute;left:0;right:100%;bottom:-5px;height:1px;background:var(--signal);transition:right .35s var(--motion-ease)}.menu a:hover{transform:translateY(-1px)}.menu a:hover:after,.menu a.current:after{right:0}.story,.feed-item,.driver-card,.probability,.schedule div,.ledger-row,.panel,.notice,.race-hero,.newsletter{transition:transform .45s var(--motion-ease),box-shadow .45s var(--motion-ease),background-color .35s ease}.story:hover,.feed-item:hover,.driver-card:hover{transform:translateY(-4px)}.driver-card{overflow:hidden}.driver-card img{transition:transform .8s var(--motion-ease),filter .5s ease}.driver-card:hover img{transform:scale(1.035);filter:saturate(1.05)}.panel:hover,.race-hero:hover{box-shadow:0 18px 45px rgba(23,24,22,.12)}.button,.signup,.calendar-actions a{transition:transform .3s var(--motion-ease),background-color .25s ease,color .25s ease}.button:hover,.calendar-actions a:hover{transform:translateY(-2px)}.section-head,.race-week-lead{overflow:hidden}.section-head:after,.race-week-lead:after{content:'';display:block;height:2px;background:var(--signal);transform:translateX(-105%);transition:transform .8s var(--motion-ease)}.section-head:hover:after,.race-week-lead:hover:after{transform:translateX(0)}@keyframes sm-enter{from{opacity:0;transform:translateY(16px)}to{opacity:1;transform:none}}}
.race-countdown{display:grid;grid-template-columns:1fr 1fr;gap:25px;margin-top:30px;padding-top:22px;border-top:1px solid rgba(233,229,219,.35)}.race-countdown strong{display:block;font:500 clamp(34px,5vw,60px)/.85 Georgia;letter-spacing:-.06em;margin:8px 0}.race-countdown #countdown-label{font:9px Arial;letter-spacing:.11em;text-transform:uppercase;opacity:.7}.calendar-actions{margin-top:25px;padding-top:18px;border-top:1px solid rgba(233,229,219,.3);display:flex;flex-wrap:wrap;gap:9px}.calendar-actions span{width:100%;font:800 9px Arial;letter-spacing:.11em;text-transform:uppercase;opacity:.7}.calendar-actions a{border:1px solid currentColor;padding:8px 10px;font:800 9px Arial;letter-spacing:.08em;text-transform:uppercase}@media(max-width:780px){.race-countdown{grid-template-columns:1fr}.calendar-actions{gap:7px}}
`;
document.head.appendChild(style);
function homepageNextRaceTimer(){const el=$('#homepage-next-race-value');if(!el)return;const target=new Date('2026-09-26T11:00:00Z');const label=$('#homepage-next-race-label');const tick=()=>{const ms=Math.max(0,target-Date.now()),d=Math.floor(ms/864e5),h=Math.floor(ms%864e5/36e5),m=Math.floor(ms%36e5/6e4),sec=Math.floor(ms%6e4/1e3);el.textContent=d+'d '+[h,m,sec].map(v=>String(v).padStart(2,'0')).join(':');if(label)label.textContent=ms?'Azerbaijan Grand Prix · Baku':'Azerbaijan GP is live'};tick();setInterval(tick,1000)}
function calendar(){if(!/calendar(?:\.html)?$|race-centre(?:\.html)?$/.test(location.pathname))return;const host=$('.hero')||$('.race-hero');if(!host||$('.calendar-actions'))return;const start='20260926T110000Z',end='20260926T130000Z',title=encodeURIComponent('2026 Azerbaijan Grand Prix · SPECTATE MOTION'),details=encodeURIComponent('Azerbaijan Grand Prix at Baku City Circuit. Race: 26 September 2026, 15:00 Baku / 16:30 IST.'),loc=encodeURIComponent('Baku City Circuit, Baku, Azerbaijan'),google='https://calendar.google.com/calendar/render?action=TEMPLATE&text='+title+'&dates='+start+'/'+end+'&details='+details+'&location='+loc,w=document.createElement('div');w.className='calendar-actions';w.innerHTML='<span>Add the Azerbaijan Grand Prix to your calendar</span><a target="_blank" rel="noreferrer" href="'+google+'">Google Calendar ↗</a>';host.appendChild(w)}
function theme(){if($('.theme-toggle'))return;const b=document.createElement('button');b.className='theme-toggle';b.innerHTML='<span class="theme-dot"></span><span class="theme-label">Dark mode</span>';($('.masthead')||$('.top'))?.appendChild(b);b.onclick=()=>{const d=document.documentElement.dataset.theme==='dark';document.documentElement.dataset.theme=d?'light':'dark';localStorage.setItem('sm-theme',d?'light':'dark')};}
function boot(){homepageNextRaceTimer();calendar();theme();document.body.classList.add('motion-ready')}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();})();