(function(){
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const style=document.createElement('style');
style.textContent=`
html{--motion-ease:cubic-bezier(.22,1,.36,1);--motion-fast:180ms;--motion-mid:520ms}
@media (prefers-reduced-motion:no-preference){
  body.motion-ready .masthead,body.motion-ready .menu,body.motion-ready .page>*{animation:sm-enter .7s var(--motion-ease) both}
  body.motion-ready .masthead{animation-delay:40ms}.masthead h1{transition:transform .7s var(--motion-ease),letter-spacing .7s var(--motion-ease)}
  .menu a{position:relative;transition:color var(--motion-fast) ease,transform var(--motion-fast) var(--motion-ease)}
  .menu a:after{content:'';position:absolute;left:0;right:100%;bottom:-5px;height:1px;background:var(--signal);transition:right .35s var(--motion-ease)}
  .menu a:hover{transform:translateY(-1px)}.menu a:hover:after,.menu a.current:after{right:0}
  .story,.feed-item,.driver-card,.probability,.schedule div,.ledger-row,.panel,.notice,.race-hero,.newsletter{transition:transform .45s var(--motion-ease),box-shadow .45s var(--motion-ease),background-color .35s ease}
  .story:hover,.feed-item:hover,.driver-card:hover{transform:translateY(-4px)}
  .driver-card{overflow:hidden}.driver-card img{transition:transform .8s var(--motion-ease),filter .5s ease}.driver-card:hover img{transform:scale(1.035);filter:saturate(1.05)}
  .panel:hover,.race-hero:hover{box-shadow:0 18px 45px rgba(23,24,22,.12)}
  .button,.signup,.calendar-actions a{transition:transform .3s var(--motion-ease),background-color .25s ease,color .25s ease}.button:hover,.calendar-actions a:hover{transform:translateY(-2px)}
  .section-head,.race-week-lead{overflow:hidden}.section-head:after,.race-week-lead:after{content:'';display:block;height:2px;background:var(--signal);transform:translateX(-105%);transition:transform .8s var(--motion-ease)}
  .section-head:hover:after,.race-week-lead:hover:after{transform:translateX(0)}
  .bar span{transform-origin:left;animation:sm-grow 1s .2s var(--motion-ease) both}
  .circuit-line{animation:sm-draw 2.2s var(--motion-ease) both}
  .reading-progress{transition:transform .08s linear}
  .mobile-drawer{transition:transform .55s var(--motion-ease)}
  .mobile-drawer a{transition:padding-left .35s var(--motion-ease),color .2s ease}.mobile-drawer a:hover{padding-left:8px}
  @keyframes sm-enter{from{opacity:0;transform:translateY(16px)}to{opacity:1;transform:none}}
  @keyframes sm-grow{from{transform:scaleX(0)}to{transform:scaleX(1)}}
  @keyframes sm-draw{from{opacity:0;clip-path:inset(0 100% 0 0)}to{opacity:1;clip-path:inset(0)}}
}
.sm-reveal{opacity:0;transform:translateY(22px);transition:opacity .75s var(--motion-ease),transform .75s var(--motion-ease)}
.sm-reveal.is-visible{opacity:1;transform:none}
@media(prefers-reduced-motion:reduce){.sm-reveal{opacity:1;transform:none!important}.circuit-line,.bar span{animation:none!important}}
.theme-toggle{position:absolute;right:0;bottom:9px;border:1px solid var(--ink);background:transparent;color:var(--ink);padding:7px 10px;font:800 8px Arial;letter-spacing:.1em;text-transform:uppercase;cursor:pointer}.theme-dot{display:inline-block;width:8px;height:8px;border-radius:50%;background:var(--signal);margin-right:6px}
.mobile-nav-toggle{display:none}.mobile-drawer{position:fixed;inset:0 0 0 auto;width:min(88vw,380px);background:var(--paper);color:var(--ink);z-index:1000;padding:22px;transform:translateX(105%);border-left:2px solid var(--ink)}.mobile-drawer.open{transform:translateX(0)}.mobile-drawer-head{display:flex;justify-content:space-between;padding-bottom:18px;border-bottom:2px solid var(--ink);font:800 9px Arial;letter-spacing:.12em}.mobile-drawer-head button{border:0;background:transparent;color:inherit;font:800 9px Arial;text-transform:uppercase}.mobile-drawer nav{display:grid}.mobile-drawer a{padding:18px 0;border-bottom:1px solid var(--line);font:500 31px/.9 Georgia;letter-spacing:-.04em}.mobile-drawer a.current{color:var(--signal)}
.reading-progress{position:fixed;top:0;left:0;width:100%;height:3px;background:var(--signal);transform:scaleX(0);transform-origin:left;z-index:1000}.reading-time{display:inline-block;margin:0 0 20px;padding:5px 8px;border:1px solid var(--line);font:800 8px Arial;letter-spacing:.12em;text-transform:uppercase}
.race-countdown{display:grid;grid-template-columns:1fr 1fr;gap:25px;margin-top:30px;padding-top:22px;border-top:1px solid rgba(233,229,219,.35)}.race-countdown strong{display:block;font:500 clamp(34px,5vw,60px)/.85 Georgia;letter-spacing:-.06em;margin:8px 0}.race-countdown #countdown-label{font:9px Arial;letter-spacing:.11em;text-transform:uppercase;opacity:.7}.circuit-mini{position:relative;min-height:110px;border:1px solid rgba(233,229,219,.3);padding:18px}.circuit-line{position:absolute;inset:22px 30px;border:2px solid #c9ee6b;border-radius:48% 25% 40% 55%;transform:rotate(-7deg)}.circuit-mini span{position:relative;margin-right:14px;font:800 8px Arial;letter-spacing:.1em;color:#c9ee6b}.circuit-mini small{position:absolute;bottom:10px;left:18px;font:8px Arial;letter-spacing:.08em;text-transform:uppercase;opacity:.65}
.credibility-filters{display:flex;align-items:center;gap:8px;flex-wrap:wrap;padding:16px 0;border-bottom:1px solid var(--line)}.credibility-filters span{font:800 9px Arial;letter-spacing:.11em;text-transform:uppercase;margin-right:6px}.credibility-filters button{border:1px solid var(--line);background:transparent;color:var(--ink);padding:7px 10px;font:800 9px Arial;letter-spacing:.08em;text-transform:uppercase;cursor:pointer}.credibility-filters button.active,.credibility-filters button:hover{background:var(--ink);color:var(--paper)}
.newsletter-form label{display:block;font:800 9px Arial;letter-spacing:.11em;text-transform:uppercase;margin-bottom:8px}.newsletter-form>div{display:flex;border-bottom:1px solid var(--ink)}.newsletter-form input{flex:1;min-width:0;border:0;background:transparent;color:var(--ink);padding:10px 0;outline:0;font:14px Georgia}.newsletter-form button{border:0;background:transparent;color:var(--ink);font:800 9px Arial;letter-spacing:.1em;text-transform:uppercase;cursor:pointer}.newsletter-form small{display:block;margin-top:8px;font:8px Arial;letter-spacing:.06em}.newsletter-success{display:grid;gap:7px;font:12px/1.4 Georgia}.newsletter-success b{font:500 28px/.9 Georgia}
.calendar-actions{margin-top:25px;padding-top:18px;border-top:1px solid rgba(233,229,219,.3);display:flex;flex-wrap:wrap;gap:9px}.calendar-actions span{width:100%;font:800 9px Arial;letter-spacing:.11em;text-transform:uppercase;opacity:.7}.calendar-actions a{border:1px solid currentColor;padding:8px 10px;font:800 9px Arial;letter-spacing:.08em;text-transform:uppercase}
html[data-theme=dark]{--paper:#10120f;--ink:#eeeae0;--forest:#1b241e;--signal:#d8f36a;--mist:#222821;--line:rgba(238,234,224,.25)}html[data-theme=dark] body{background:var(--paper);color:var(--ink)}html[data-theme=dark] .intro,html[data-theme=dark] .story p,html[data-theme=dark] .section-head p,html[data-theme=dark] .feed-item p,html[data-theme=dark] .assumption{color:#c7c5bc}
html[data-theme=dark] .panel,html[data-theme=dark] .race-hero{background:var(--forest);color:var(--ink)}html[data-theme=dark] .panel .eyebrow,html[data-theme=dark] .race-hero .eyebrow{color:var(--signal)}html[data-theme=dark] .panel p,html[data-theme=dark] .race-hero p{color:#c7cfc7;opacity:.9}html[data-theme=dark] .race-detail{border-left-color:rgba(238,234,224,.25)}html[data-theme=dark] .notice{background:#191d19;color:var(--ink)}html[data-theme=dark] .sponsor-panel{background:#0b0d0b;color:var(--ink)}html[data-theme=dark] .sponsor-panel p{color:#c7c5bc}html[data-theme=dark] .newsletter{background:#d8f36a;color:#10120f}html[data-theme=dark] .newsletter .eyebrow{color:#10120f}html[data-theme=dark] .signup{border-color:#10120f}html[data-theme=dark] .table th{border-color:var(--ink)}html[data-theme=dark] .button{background:#d8f36a;color:#10120f!important}html[data-theme=dark] .meta-row,html[data-theme=dark] .freshness{color:#bfc3b9}html[data-theme=dark] .confirmed{color:#6bd69c}html[data-theme=dark] .reported{color:#f08a62}html[data-theme=dark] .speculation{color:#c38ee8}html[data-theme=dark] .analysis{color:#75b6df}html[data-theme=dark] ::selection{background:#d8f36a;color:#10120f}
@media(max-width:780px){.theme-toggle{right:0;bottom:8px}.mobile-nav-toggle{position:fixed;display:flex;align-items:center;gap:4px;flex-direction:column;right:14px;bottom:14px;width:52px;height:52px;border:1px solid var(--ink);background:var(--paper);color:var(--ink);z-index:1001;padding:9px;cursor:pointer}.mobile-nav-toggle span{display:block;width:22px;height:1px;background:currentColor}.mobile-nav-toggle b{font:800 7px Arial;letter-spacing:.1em;text-transform:uppercase}.menu{display:none}.race-countdown{grid-template-columns:1fr}.credibility-filters{position:sticky;top:0;background:var(--paper);z-index:20}.calendar-actions{gap:7px}}
`;
document.head.appendChild(style);
const saved=localStorage.getItem('sm-theme');if(saved)document.documentElement.dataset.theme=saved;
function theme(){if($('.theme-toggle'))return;const b=document.createElement('button');b.className='theme-toggle';b.innerHTML='<span class="theme-dot"></span><span class="theme-label">Dark mode</span>';($('.masthead')||$('.top'))?.appendChild(b);const sync=()=>{const d=document.documentElement.dataset.theme==='dark';b.querySelector('.theme-label').textContent=d?'Light mode':'Dark mode'};b.onclick=()=>{const d=document.documentElement.dataset.theme==='dark';document.documentElement.dataset.theme=d?'light':'dark';localStorage.setItem('sm-theme',d?'light':'dark');sync()};sync()}
function mobile(){const m=$('.menu');if(!m||$('.mobile-nav-toggle'))return;const t=document.createElement('button');t.className='mobile-nav-toggle';t.innerHTML='<span></span><span></span><span></span><b>Menu</b>';document.body.appendChild(t);const d=document.createElement('aside');d.className='mobile-drawer';d.innerHTML='<div class="mobile-drawer-head"><span>SPECTATE MOTION</span><button>Close ×</button></div><nav>'+m.innerHTML+'</nav>';document.body.appendChild(d);const close=()=>d.classList.remove('open');t.onclick=()=>d.classList.toggle('open');d.querySelector('button').onclick=close;$$('a',d).forEach(a=>a.onclick=close)}
function countdown(){const lead=$('.race-week-lead');if(!lead||$('.race-countdown'))return;const x=document.createElement('div');x.className='race-countdown';x.innerHTML='<div><span class="eyebrow">Race-week signal</span><strong id="countdown-value">--:--:--</strong><span id="countdown-label">Until the next session</span></div><div class="circuit-mini"><div class="circuit-line"></div><span>S1</span><span>S2</span><span>S3</span><small>Track profile · not live telemetry</small></div>';lead.appendChild(x);const ev=[['Qualifying',new Date('2026-08-22T19:30:00+05:30')],['Grand Prix',new Date('2026-08-23T18:30:00+05:30')]];const tick=()=>{const n=new Date(),e=ev.find(v=>v[1]>n)||ev[ev.length-1],ms=Math.max(0,e[1]-n),h=Math.floor(ms/36e5),m=Math.floor(ms%36e5/6e4),s=Math.floor(ms%6e4/1e3);$('#countdown-value').textContent=[h,m,s].map(v=>String(v).padStart(2,'0')).join(':');$('#countdown-label').textContent='Until '+e[0]+' · IST'};tick();setInterval(tick,1000)}
function filters(){const f=$('.feed');if(!f||$('.credibility-filters'))return;const items=$$('.feed-item,.signing-card,.signing-small');const w=document.createElement('div');w.className='credibility-filters';w.innerHTML='<span>Filter desk</span><button class="active" data-f="all">All</button><button data-f="confirmed">Confirmed</button><button data-f="reported">Reported</button><button data-f="speculation">Speculation</button>';f.parentElement.insertBefore(w,f);items.forEach(i=>{const p=$('.pill',i),s=p?.textContent.toLowerCase()||'';i.dataset.filterStatus=i.dataset.status||i.dataset.filterStatus||(s.includes('confirmed')?'confirmed':s.includes('reported')?'reported':s.includes('speculation')?'speculation':'all')});w.onclick=e=>{const b=e.target.closest('button');if(!b)return;$$('button',w).forEach(q=>q.classList.remove('active'));b.classList.add('active');items.forEach(i=>{i.hidden=b.dataset.f!=='all'&&i.dataset.filterStatus!==b.dataset.f})}}
function reading(){if(!/guide-2026(?:\.html)?$|editorial(?:\.html)?$/.test(location.pathname))return;if($('.reading-progress'))return;const mins=Math.max(1,Math.ceil(document.body.innerText.replace(/\s+/g,' ').split(' ').length/220)),intro=$('.intro');if(intro&&!$('.reading-time')){const r=document.createElement('span');r.className='reading-time';r.textContent=mins+' min read';intro.after(r)}const b=document.createElement('div');b.className='reading-progress';document.body.appendChild(b);const update=()=>{const h=document.documentElement.scrollHeight-innerHeight;b.style.transform='scaleX('+(h>0?Math.min(1,scrollY/h):0)+')'};addEventListener('scroll',update,{passive:true});update()}
function calendar(){if(!/calendar(?:\.html)?$|race-centre(?:\.html)?$/.test(location.pathname))return;const host=$('.hero')||$('.race-hero');if(!host||$('.calendar-actions'))return;const start='20260823T153000Z',end='20260823T180000Z',title=encodeURIComponent('2026 Dutch Grand Prix · SPECTATE MOTION'),details=encodeURIComponent('Dutch Grand Prix at Zandvoort. Check official Formula 1 timing before relying on this entry.'),loc=encodeURIComponent('Circuit Zandvoort, Netherlands'),google='https://calendar.google.com/calendar/render?action=TEMPLATE&text='+title+'&dates='+start+'/'+end+'&details='+details+'&location='+loc,ics='BEGIN:VCALENDAR\nVERSION:2.0\nPRODID:-//SPECTATE MOTION//EN\nBEGIN:VEVENT\nUID:spectate-dutch-gp-2026\nDTSTART:'+start+'\nDTEND:'+end+'\nSUMMARY:2026 Dutch Grand Prix · SPECTATE MOTION\nLOCATION:Circuit Zandvoort, Netherlands\nEND:VEVENT\nEND:VCALENDAR',w=document.createElement('div');w.className='calendar-actions';w.innerHTML='<span>Add the weekend to your calendar</span><a target="_blank" rel="noreferrer" href="'+google+'">Google Calendar ↗</a><a download="spectate-dutch-gp-2026.ics" href="data:text/calendar;charset=utf-8,'+encodeURIComponent(ics)+'">Download iCal ↓</a>';host.appendChild(w)}
function newsletter(){const n=$('.newsletter'),s=$('.signup',n);if(!n||!s||$('.newsletter-form'))return;const existing=localStorage.getItem('sm-newsletter-email');if(existing){s.innerHTML='<div class="newsletter-success"><b>You’re on the desk.</b><span>'+existing+' is saved for the briefing.</span></div>';return}s.innerHTML='<form class="newsletter-form"><label for="sm-email">Get the briefing</label><div><input id="sm-email" type="email" required autocomplete="email" placeholder="your@email.com"><button>Join ↗</button></div><small>No provider is connected yet; your email is only stored locally in this browser.</small></form>';$('.newsletter-form').onsubmit=e=>{e.preventDefault();const v=$('#sm-email').value.trim();if(!v)return;localStorage.setItem('sm-newsletter-email',v);s.innerHTML='<div class="newsletter-success"><b>You’re on the desk.</b><span>'+v+' is saved locally. Connect Resend/ConvertKit later to turn this into a real mailing list.</span></div>'}}
function motion(){document.body.classList.add('motion-ready');const targets=$$('.story,.feed-item,.driver-card,.probability,.schedule div,.ledger-row,.notice,.panel,.section-head,.race-week-lead,.newsletter,.source-ledger');targets.forEach((el,i)=>{el.classList.add('sm-reveal');el.style.transitionDelay=Math.min(i%6*55,275)+'ms'});if(matchMedia('(prefers-reduced-motion: reduce)').matches){targets.forEach(el=>el.classList.add('is-visible'));return}if(!('IntersectionObserver' in window)){targets.forEach(el=>el.classList.add('is-visible'));return}const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');io.unobserve(e.target)}}),{threshold:.12,rootMargin:'0px 0px -8%'});targets.forEach(el=>io.observe(el));}
document.addEventListener('DOMContentLoaded',()=>{theme();mobile();filters();reading();calendar();newsletter();motion()});
})();
