const STORIES = [
{status:"confirmed",source:"Reuters / Formula 1",kicker:"Singapore · Sprint",title:"Verstappen wins chaotic Singapore Sprint as nine cars retire",description:"Max Verstappen won ahead of Lewis Hamilton and Charles Leclerc after heavy rain delayed the start and nine cars retired — a Sprint record.",published:"2026-10-10T10:32:39Z",link:"https://www.reuters.com/sports/formula1/verstappen-wins-singapore-sprint-after-chaotic-start-wet-conditions-2026-10-10/",body:["Heavy rain delayed the start by more than 30 minutes before Verstappen secured the win.","Hamilton and Leclerc completed a Ferrari double podium. Championship leader Kimi Antonelli finished fourth.","George Russell crashed at the final turn, while the two McLaren drivers collided on the last lap. Nine cars retired, a record for a Sprint."],keyFacts:["Verstappen P1","Hamilton P2","Leclerc P3","Antonelli P4","Nine retirements · Sprint record","Grand Prix qualifying still to come"],context:"Reuters report published 10 October 2026 and official Formula 1 session reporting.",whyItMatters:"The result gives Verstappen momentum and Ferrari a double podium, but the Grand Prix grid is still to be set in qualifying.",whatNext:"Singapore Grand Prix qualifying is Saturday evening; the 62-lap race is Sunday at 17:30 IST."},
{status:"confirmed",source:"Formula 1 / FIA",kicker:"Sepang · Race",title:"Verstappen wins rain-hit Sepang thriller",description:"Max Verstappen beat Kimi Antonelli by 2.307s, with Lewis Hamilton third and George Russell retiring late.",published:"2026-10-04T10:38:00Z",link:"https://www.formula1.com/",body:["Max Verstappen converted pole into victory at Sepang for his first win of 2026.","Kimi Antonelli finished second and Lewis Hamilton third. Charles Leclerc was fourth and Isack Hadjar fifth.","George Russell retired with five laps remaining after a rain-delayed start and late Safety Car."],keyFacts:["Verstappen P1","Antonelli P2 · +2.307s","Hamilton P3 · +4.919s","Leclerc P4","Hadjar P5","Russell DNF"],context:"Official Formula 1 and FIA race classification.",whyItMatters:"Verstappen delivered Red Bull Ford Powertrains its first 2026 victory while Antonelli extended his championship lead.",whatNext:"Singapore is Round 17 on October 9–11."},
{status:"confirmed",source:"Formula 1",kicker:"Championship · After Round 16",title:"Antonelli stretches championship lead to 84 points",description:"Kimi Antonelli moves to 320 points after P2 in Malaysia; George Russell remains on 236 after his late retirement.",published:"2026-10-05T08:00:00Z",link:"https://www.formula1.com/en/results/2026/driver",body:["Antonelli's second place takes him to 320 points. Russell remains on 236, leaving an 84-point gap.","Lewis Hamilton is third on 214. Charles Leclerc has 191, while Lando Norris and Max Verstappen are level on 188."],keyFacts:["Antonelli 320","Russell 236","Hamilton 214","Leclerc 191","Norris 188","Verstappen 188"],context:"Current Formula 1 driver standings after Round 16.",whyItMatters:"Russell's DNF materially changed the title fight.",whatNext:"Singapore provides the next championship swing."},
{status:"reported",source:"FIA / Formula 1",kicker:"Technical · FIA review",title:"FIA to investigate software issue behind chaotic wet start",description:"Multiple cars experienced power-related problems during the formation lap in heavy rain, forcing an aborted start and delay.",published:"2026-10-05T04:47:00Z",link:"https://www.formula1.com/",body:["The formation lap was disrupted by software-related power delivery problems in heavy rain.","The start procedure was aborted and teams worked on the cars before the race eventually got underway.","The FIA has indicated that the incident will be investigated; SPECTATE is not treating the cause as finally established."],keyFacts:["Multiple cars affected","Formation lap interrupted","Start aborted","Investigation ongoing"],context:"Formula 1 and FIA reporting around the Sepang wet start.",whyItMatters:"The incident raises questions about wet-weather robustness of the 2026 control systems.",whatNext:"Watch for formal FIA findings."},
{status:"confirmed",source:"Formula 1",kicker:"Next round · Singapore",title:"Singapore Grand Prix brings the Sprint format next weekend",description:"Round 17 runs October 9–11 at Marina Bay, with Sprint Qualifying Friday, the Sprint and Grand Prix qualifying Saturday, and the race Sunday.",published:"2026-10-05T08:30:00Z",link:"https://www.formula1.com/",body:["Singapore hosts Round 17 on October 9–11 and uses the Sprint format.","FP1 is Friday at 16:30 local, Sprint Qualifying at 20:30. The Sprint starts Saturday at 17:00, followed by Grand Prix qualifying at 21:00.","The 62-lap Grand Prix starts Sunday at 20:00 Singapore time, 17:30 IST."],keyFacts:["9–11 October","FP1 · 14:00 IST","Sprint Qualifying · 18:00 IST","Sprint · 14:30 IST Saturday","Qualifying · 18:30 IST Saturday","Race · 17:30 IST Sunday"],context:"Official Formula 1 Singapore timetable.",whyItMatters:"The Sprint format compresses the setup window at Marina Bay.",whatNext:"Singapore practice and Sprint Qualifying set the first competitive order."}
];
export default function handler(req,res){
  res.setHeader("Cache-Control","s-maxage=120, stale-while-revalidate=300");
  res.setHeader("Access-Control-Allow-Origin","*");
  res.status(200).json({
    updatedAt:"2026-10-10T10:32:39Z",
    stories:STORIES,
    policy:"Formula 1, FIA, teams and drivers are primary sources. Confirmed facts are separated from SPECTATE analysis and reported developments."
  });
}